/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ChatBoxLeft: typeof import('./src/components/chatBox/left/chatBox-Left.vue')['default']
    ChatBoxLeftItem: typeof import('./src/components/chatBox/left/chatBox-Left-Item.vue')['default']
    ChatBoxLeftList: typeof import('./src/components/chatBox/left/chatBox-Left-List.vue')['default']
    ChatBoxLeftSearch: typeof import('./src/components/chatBox/left/chatBox-Left-Search.vue')['default']
    ChatBoxRight: typeof import('./src/components/chatBox/right/chatBox-right.vue')['default']
    ChatBoxRightFile: typeof import('./src/components/chatBox/right/chatBox-right-file.vue')['default']
    ChatBoxRightImage: typeof import('./src/components/chatBox/right/chatBox-right-image.vue')['default']
    ChatBoxRightPerson: typeof import('./src/components/chatBox/right/chatBox-right-person.vue')['default']
    ChatBoxRightStatus: typeof import('./src/components/chatBox/right/chatBox-right-status.vue')['default']
    ChatBoxRightTips: typeof import('./src/components/chatBox/right/chatBox-right-tips.vue')['default']
    ChatMessage: typeof import('./src/components/chatBox/content/chatMessage.vue')['default']
    ChatRoom: typeof import('./src/components/chatBox/content/chatRoom.vue')['default']
    Confirm: typeof import('./src/components/chatBox/content/message/Confirm.vue')['default']
    ContactModal: typeof import('./src/components/ContactModal.vue')['default']
    FileList: typeof import('./src/components/contact/FileList.vue')['default']
    FindList: typeof import('./src/components/chatBox/content/message/FindList.vue')['default']
    ImageView: typeof import('./src/components/chatBox/content/message/ImageView.vue')['default']
    MessageItem: typeof import('./src/components/chatBox/content/message/MessageItem.vue')['default']
    ModifyInformation: typeof import('./src/components/company/ModifyInformation.vue')['default']
    QuickMsg: typeof import('./src/components/contact/QuickMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./src/components/templates/SelectInput.vue')['default']
    SelectItem: typeof import('./src/components/contact/SelectItem.vue')['default']
    TemplateList: typeof import('./src/components/chatBox/content/message/TemplateList.vue')['default']
    ToggleComapny: typeof import('./src/components/company/ToggleComapny.vue')['default']
    ToggleComapnyCarousel: typeof import('./src/components/company/ToggleComapnyCarousel.vue')['default']
    ToggleCompanyCarousel: typeof import('./src/components/company/ToggleCompanyCarousel.vue')['default']
    ToggleUserCompany: typeof import('./src/components/company/ToggleUserCompany.vue')['default']
    WASelect: typeof import('./src/components/templates/WASelect.vue')['default']
  }
}
